### ISSUE TITLE
Greetings

### ISSUE THREAD

**Issue by zweihan** [matpil/FarmaciaDiTurnoLameziaTerme#1]
Hi Matpil,
Apologies for the unusual way of reaching out to you, I don't know how else I can reach you.

I am approaching you regarding an issue you have posted about ElasticAPM last year.
https://discuss.elastic.co/t/elastic-apm-with-playframework/172122

I am currently going through the same steps, of attempting to integrate ElasticAPM with Cinnamon on Play framework. 

I tried following your steps but I still can't get it to work. I wonder, besides the `Filter` and the cinnamon opentracing config, what else have you done? If you have some references that you can point me to, that would be great.

Thanks in advance!

Weihan

**Comment by matpil** [comment]
Hi,
To trace incoming calls it is enough.
To trace outcoming calls you have to create “manually” a span.
However i’m still waiting for apm playframework official support....

I hope that my answer helps you

Regards

Il giorno mer 15 apr 2020 alle 12:24 zweihan <notifications@github.com> ha
scritto:

**Comment by zweihan** [comment]
Hi, 
I followed your steps but ended up having some errors
```
java.lang.ClassCastException: cinnamon.opentracing.TraceLocal$ContextOnlySpan cannot be cast to co.elastic.apm.opentracing.ApmSpan
	at co.elastic.apm.opentracing.ApmScopeManager.activate(ApmScopeManager.java:38)
	at co.elastic.apm.opentracing.ApmScopeManager.activate(ApmScopeManager.java:59)
	at cinnamon.opentracing.TraceLocal.activateContext(TraceLocal.java:334)
```

**Comment by matpil** [comment]
uhm...
maybe something was changed on new apm api?
unfortunately I have lightbend subscription no more and I can't test again.

Regards



Il giorno gio 16 apr 2020 alle ore 03:50 zweihan <notifications@github.com>
ha scritto:
